apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical
  namespace: restricted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical
  template:
    metadata:
      labels:
        app: infisical
    spec:
      containers:
        - name: infisical
          image: infisical/infisical:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: encryption_key
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: auth_secret
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: mongo_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: resis_url
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: NEXT_PUBLIC_POSTHOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: posthog_api_key
            - name: BAKED_NEXT_PUBLIC_POSTHOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: posthog_api_key
            - name: NEXT_PUBLIC_INTERCOM_ID
              value: "intercom-id"
            - name: BAKED_NEXT_PUBLIC_INTERCOM_ID
              value: "intercom-id"
            - name: PORT
              value: "8080"
            - name: HTTPS_ENABLED
              value: "false"
            - name: NODE_ENV
              value: "production"
            - name: STANDALONE_BUILD
              value: "true"
            - name: TELEMETRY_ENABLED
              value: "true"
            - name: CLIENT_ID_GITHUB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: github_client_id
            - name: CLIENT_SECRET_GITHUB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: github_secret
            - name: SITE_URL
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: site_url
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: smtp_host
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: smtp_username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: smtp_password
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SECURE
              value: "true"
            - name: SMTP_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: smtp_from_address
            - name: SMTP_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: infisical-secrets
                  key: smtp_from_name
