apiVersion: v1
kind: Service
metadata:
  name: redis-lb
  namespace: databases
spec:
  selector:
    app: redis
  ports:
    - name: redis-db
      port: 6379
      targetPort: 6379
  type: LoadBalancer
  loadBalancerIP: 10.10.0.193
