apiVersion: v1
kind: Service
metadata:
  name: maybe-lb
  namespace: default
spec:
  selector:
    app: maybe
  ports:
    - name: maybe-web
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 10.10.0.147
