apiVersion: v1
kind: Service
metadata:
  name: dokuwiki-lb
  namespace: default
spec:
  selector:
    app: dokuwiki
  ports:
    - name: dokuwiki-web
      port: 80
      targetPort: 80
    - name: dokuwiki-https
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 10.10.0.157
