apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: default
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2.5.307
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: wikijs-web
            protocol: TCP
          env:
            - name: DB_HOST
              value: wiki-sql.default.svc.cluster.local
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wikijs-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wikijs-secrets
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wikijs-secrets
                  key: DB_NAME
          readinessProbe:
            httpGet:
              port: wikijs-web
              path: /
