apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-sql
  namespace: default
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: wiki-sql
  template:
    metadata:
      labels:
        app: wiki-sql
    spec:
      volumes:
        - name: wiki-sql-storage
          persistentVolumeClaim:
            claimName: wiki-sql-pvc
      containers:
        - name: wiki-sql
          image: postgres:17.5
          imagePullPolicy: Always
          ports:
          - containerPort: 5432
            name: wiki-sql
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wikijs-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wikijs-secrets
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wikijs-secrets
                  key: DB_NAME
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: wiki-sql-storage
