apiVersion: v1
kind: Service
metadata:
  name: nextcloud-lb
  namespace: cloud
spec:
  selector:
    app: nextcloud
  ports:
    - name: nextcloud-web
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.10.0.144
