apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-netcloud
  namespace: cloud
  labels:
    app: redis-netcloud
spec:
  selector:
    matchLabels:
      app: redis-netcloud
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-netcloud
    spec:
      volumes:
        - name: redis-netcloud-storage
          persistentVolumeClaim:
            claimName: redis-netcloud-pvc
      containers:
      - name: redis-netcloud
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis-netcloud
        volumeMounts:
        - name: redis-netcloud-storage
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-netcloud
  namespace: cloud
  labels:
    app: redis-netcloud
spec:
  ports:
    - port: 6379
  selector:
    app: redis-netcloud
