apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-nextcloud
  namespace: cloud
  labels:
    app: redis-nextcloud
spec:
  selector:
    matchLabels:
      app: redis-nextcloud
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-nextcloud
    spec:
      volumes:
        - name: redis-nextcloud-storage
          persistentVolumeClaim:
            claimName: redis-nextcloud-pvc
      containers:
      - name: redis-nextcloud
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis-nextcloud
        volumeMounts:
        - name: redis-nextcloud-storage
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-nextcloud
  namespace: cloud
  labels:
    app: redis-nextcloud
spec:
  ports:
    - port: 6379
  selector:
    app: redis-nextcloud
