apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cloud
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cloud
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
