apiVersion: v1
kind: Service
metadata:
  name: exdiary-lb
  namespace: fitness
spec:
  selector:
    app: exdiary
  ports:
    - name: exdiary-web
      port: 80
      targetPort: 8851
  type: LoadBalancer
  loadBalancerIP: 10.10.0.132
