apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exdiary-pvc
  namespace: fitness
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
