apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: immichsecrets
  namespace: default
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: http://infisical-lb.infisical.svc.cluster.local/api
  resyncInterval: 300
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-immich
        secretNamespace: restricted
      secretsScope:
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: immich-env # <-- the name of kubernetes secret that will be created
    secretNamespace: cloud # <-- where the kubernetes secret should be created
