apiVersion: v1
kind: Service
metadata:
  name: immich-lb
  namespace: cloud
spec:
  selector:
    app: immich
  ports:
    - name: immich-web
      port: 80
      targetPort: 2283
  type: LoadBalancer
  loadBalancerIP: 10.10.0.162
---
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: cloud
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: immich
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-immich
  namespace: cloud
  labels:
    app: immich
spec:
  ports:
    - port: 5432
  selector:
    app: immich

