apiVersion: v1
kind: Service
metadata:
  name: openproject-lb
  namespace: default
spec:
  selector:
    app: openproject
  ports:
    - name: openproject-web
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.10.0.143
