apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fitness
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: wgerredis-storage
          persistentVolumeClaim:
            claimName: wgerredis-pvc
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: wgerredis-storage
          mountPath: /data
