apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: default
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      volumes:
        - name: bookstack-storage
          persistentVolumeClaim:
            claimName: bookstack-pvc
      containers:
        - name: bookstack
          image: lscr.io/linuxserver/bookstack
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: web
            protocol: TCP
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: "Etc/UTC"
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: APP_URL
            - name: DB_HOST
              value: mysql-lb.databases.svc.cluster.local
            - name: DB_PORT
              value: '3306'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: DB_PASS
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: DB_DATABASE
            - name: LDAP_BASE_DN
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_BASE_DN
            - name: LDAP_DISPLAY_NAME_ATTRIBUTE
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_DISPLAY_NAME_ATTRIBUTE
            - name: LDAP_DN
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_DN
            - name: LDAP_EMAIL_ATTRIBUTE
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_EMAIL_ATTRIBUTE
            - name: LDAP_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_PASS
            - name: LDAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_SERVER
            - name: LDAP_START_TLS
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_START_TLS
            - name: LDAP_THUMBNAIL_ATTRIBUTE
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_THUMBNAIL_ATTRIBUTE
            - name: LDAP_USER_FILTER
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_USER_FILTER
            - name: LDAP_VERSION
              valueFrom:
                secretKeyRef:
                  name: bookstack-secrets
                  key: LDAP_VERSION
            - name: APP_DEBUG
              value: 'true'
          readinessProbe:
            httpGet:
              port: web
              path: /
          volumeMounts:
            - mountPath: "/config"
              name: bookstack-storage
