apiVersion: v1
kind: Service
metadata:
  name: bookstack-lb
  namespace: default
spec:
  selector:
    app: bookstack
  ports:
    - name: bookstack-web
      port: 80
      targetPort: 80
    - name: bookstack-https
      port: 443
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.10.0.156
