apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-pvc
  namespace: restricted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
