apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
  namespace: databases
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: LoadBalancer
  loadBalancerIP: 10.10.0.192
