apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-pvc
  namespace: restricted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi