apiVersion: v1
kind: Service
metadata:
  name: infisical-lb
  namespace: restricted
spec:
  selector:
    app: infisical
  ports:
    - name: infisical-http
      port: 80
      targetPort: 8080
    - name: infisical-web
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 10.10.0.139
