apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infisical-postgres-pvc
  namespace: infisical
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infisical-redis-pvc
  namespace: infisical
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
