apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: databases
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: Always
          resources:
            limits:
              memory: "800Mi"
#             cpu: "500m"
            requests:
              memory: "300Mi"
#             cpu: "300m"
          ports:
          - containerPort: 3306
            name: db
            protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases-root
                  key: MYSQL_ROOT_PASSWORD
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-storage
