apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
  namespace: databases
spec:
  selector:
    app: mysql
  ports:
    - name: mysql-db
      port: 3306
      targetPort: 3306
  type: LoadBalancer
  loadBalancerIP: 10.10.0.190
