apiVersion: v1
kind: Service
metadata:
  name: mealie-lb
  namespace: cloud
spec:
  selector:
    app: mealie
  ports:
    - name: mealie-web
      port: 80
      targetPort: 9000
  type: LoadBalancer
  loadBalancerIP: 10.10.0.164
