apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  namespace: fitness
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      volumes:
        - name: tracker-storage
          persistentVolumeClaim:
            claimName: tracker-pvc
      containers:
        - name: tracker
          image: ghcr.io/jovandeginste/workout-tracker:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: tracker-web
            protocol: TCP
          readinessProbe:
            httpGet:
              port: tracker-web
              path: /
          volumeMounts:
            - mountPath: "/data"
              name: tracker-storage
