apiVersion: v1
kind: Service
metadata:
  name: tracker-lb
  namespace: fitness
spec:
  selector:
    app: tracker
  ports:
    - name: tracker-web
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 10.10.0.133
