apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracker-pvc
  namespace: fitness
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
