apiVersion: v1
kind: Service
metadata:
  name: gitea-lb
  namespace: cicd
spec:
  selector:
    app: gitea
  ports:
    - name: gitea-web
      port: 80
      targetPort: 3000
    - name: gitea-ssh
      port: 22
      targetPort: 22
  type: LoadBalancer
  loadBalancerIP: 10.10.0.111
