apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: restricted
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
      containers:
        - name: nextcloud
          image: nextcloud
          imagePullPolicy: Always
          ports:
          - containerPort: 443
            name: web
            protocol: TCP
          volumeMounts:
          - mountPath: "/var/www/html"
            name: nextcloud-storage
            subPath: html
          - mountPath: "/data"
            name: nextcloud-storage
            subPath: data
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mysql-lb.databases.svc.cluster.local"
          readinessProbe:
            httpGet:
              port: web
              path: 443