apiVersion: v1
kind: Service
metadata:
  name: nextcloud-lb
  namespace: restricted
spec:
  selector:
    app: nextcloud
  ports:
    - name: nextcloud-web
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 10.10.0.144