apiVersion: v1
kind: Service
metadata:
  name: ipam-lb
  namespace: default
spec:
  selector:
    app: ipam
  ports:
    - name: ipam-web
      port: 80
      targetPort: 80
    - name: ipam-https
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 10.10.0.154