apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-pvc
  namespace: monitor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-web-pvc
  namespace: monitor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi


