apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: monitor
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: zabbix-http
            protocol: TCP
          env:
            - name: ZBX_SERVER_HOST
              value: zabbix-server-lb.monitor.svc.cluster.local
            - name: DB_SERVER_HOST
              value: postgres-lb.databases.svc.cluster.local
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: zabbix-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER 
              valueFrom:
                secretKeyRef:
                  name: zabbix-secrets
                  key: POSTGRES_USER
          
