apiVersion: v1
kind: Service
metadata:
  name: actualbudget-lb
  namespace: restricted
spec:
  selector:
    app: actualbudget
  ports:
    - name: actual-web
      port: 80
      targetPort: 5006
  type: LoadBalancer
  loadBalancerIP: 10.10.0.142
